name: 'autobase-action'
description: 'Automatically rebases a PR with a specific label onto the default branch.'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  label:
    description: 'Label to filter pull requests'
    required: false
    default: 'autobase'
  required-approvals:
    description: 'The number of required approvals before a PR can be rebased'
    required: false
    default: '0'
  base-branch:
    description: 'The base branch to use'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
